[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Automatically fetch contract sources from Etherscan
auto_fetch_sources = true


# Solidity compiler settings
[compiler]
solc_version = "0.8.0"



# Wallet configuration
[wallet]
private_key = "${PRIVATE_KEY}"
mnemonic = "${MNEMONIC}"